name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

env:
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD || 'postgres' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Установка Docker и Docker Compose
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Maven Wrapper
        run: |
          if [ ! -f "mvnw" ]; then
            mvn -N wrapper:wrapper -Dmaven=3.9.6
          fi
          chmod +x mvnw
          ./mvnw --version

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            target/
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: ./mvnw clean package -DskipTests

      - name: Build Docker containers
        run: docker-compose -f docker/docker-compose.yml build

      # Остальные шаги остаются без изменений
      - name: Save Docker images
        run: |
          mkdir -p docker-images
          docker save -o docker-images/backend.tar weather-app
          docker save -o docker-images/postgres.tar postgres:13-alpine

      - name: Upload Docker images
        uses: actions/upload-artifact@v4
        with:
          name: docker-images
          path: docker-images/*.tar
          retention-days: 1

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Download Docker images
        uses: actions/download-artifact@v4
        with:
          name: docker-images
          path: docker-images

      - name: Load Docker images
        run: |
          docker load -i docker-images/backend.tar
          docker load -i docker-images/postgres.tar

      - name: Start services
        run: |
          docker-compose -f docker/docker-compose.yml up -d
          sleep 15
          docker-compose ps

      - name: Run health checks
        run: |
          curl -s http://localhost:8080/health | jq .
          curl -s http://localhost:8080/ping
          docker-compose exec postgres pg_isready -U postgres

      - name: Cleanup
        if: always()
        run: |
          docker-compose -f docker/docker-compose.yml down
          docker system prune -f